--QUERY AUDITORIA PRESIDECIAL

WITH "/CMSBE/EPTYPT" AS (SELECT "CASETYPETEXT"."MANDT" AS "MANDT",
	 "CASETYPETEXT"."SPRAS" AS "LANGUAGE",
	 "CASETYPETEXT"."CASE_TYPE" AS "CASETYPE",
	 "CASETYPETEXT"."CASE_TYPE_DESC" AS "CASETYPEDESC" 
	FROM "SAPHANADB"."/CMSBE/CT_001T" "CASETYPETEXT" 
	where "CASETYPETEXT"."SPRAS" ='S'
), "/CMSBE/EPTYP" AS (SELECT
	 "CASETYPE"."MANDT" AS "MANDT",
	 "CASETYPE"."CASE_TYPE" AS "CASETYPE",
	 "=A0"."CASETYPEDESC" AS "CASETYPEDESC" 
	FROM "SAPHANADB"."/CMSBE/CT_001" "CASETYPE" 
	LEFT OUTER MANY TO ONE JOIN "/CMSBE/EPTYPT" "=A0" ON ( "CASETYPE"."MANDT" = "=A0"."MANDT" 
		AND "CASETYPE"."CASE_TYPE" = "=A0"."CASETYPE" )
), IBUSINESSPARTNER_VIEW AS (SELECT
	 "BUT000"."CLIENT" AS "MANDT",
	 "BUT000"."PARTNER" AS "BUSINESSPARTNER",
	 "BUT000"."TYPE" AS "BUSINESSPARTNERCATEGORY",
	 "BUT000"."PARTNER_GUID" AS "BUSINESSPARTNERUUID",
	 CASE WHEN "BUT000"."TYPE" = N'1' THEN ( RTRIM( RTRIM ( "BUT000"."NAME_FIRST" ) || RPAD( '',1, NCHAR( 32) ) || RTRIM ( "BUT000"."NAME_LAST" ) ) ) 
	      WHEN "BUT000"."TYPE" = N'2' THEN ( RTRIM( RTRIM ( "BUT000"."NAME_ORG1" ) || RPAD( '',1, NCHAR( 32) ) || RTRIM ( "BUT000"."NAME_ORG2" ) ) ) 
	      WHEN "BUT000"."TYPE" = N'3' THEN ( RTRIM( RTRIM ( "BUT000"."NAME_GRP1" ) || RPAD( '',1, NCHAR( 32) ) || RTRIM ( "BUT000"."NAME_GRP2" ) ) ) 
	 END AS "BUSINESSPARTNERFULLNAME",
	 "BUT000"."NATPERS" AS "ISNATURALPERSON",
	 "BUT000"."XSEXF" AS "ISFEMALE",
	 "BUT000"."XSEXM" AS "ISMALE",
	 "BUT000"."BU_GROUP" AS "BUSINESSPARTNERGROUPING",
	 "BUT000"."BPKIND" AS "BUSINESSPARTNERTYPE",
	 N'X' AS "ISACTIVEENTITY",
	 "BUT000"."BIRTHDT" AS "BIRTHDATE",
	 "BUT000"."NATIO" AS "BUSPARTNATIONALITY",
	 "BUT000"."CNDSC" AS "NONRESIDENTCOMPANYORIGINCNTRY",
	 "BUT000"."GENDER" AS "GENDERCODENAME" ,
	 "BUT000"."NAME_LST2" AS "ADDITIONALLASTNAME",
	 "BUT000"."TITLE" AS "FORMOFADDRESS",
	 "BUT000"."NAME_LAST" AS "LASTNAME"
	FROM "SAPHANADB"."BUT000" "BUT000" 
	--WHERE "BUT000"."LANGU_CORR" = 'S'
), "/CMSBE/MDPAT" AS (SELECT
	 "MD_PATIENT"."MANDT" AS "MANDT",
	 "MD_PATIENT"."DB_KEY" AS "DBKEY",
	 "MD_PATIENT"."PAT_KEY" AS "PATKEY",
	 "MD_PATIENT"."PARTNER" AS "PARTNER",
	 "MD_PATIENT"."PAT_MERGED" AS "PATMERGED",
	 "=A0"."BUSINESSPARTNERFULLNAME" AS "BUSINESSPARTNERFULLNAME" 
	FROM "SAPHANADB"."/CMSBE/MDPATIENT" "MD_PATIENT" 
	LEFT OUTER MANY TO ONE JOIN IBUSINESSPARTNER_VIEW "=A0" ON ( "MD_PATIENT"."MANDT" = "=A0"."MANDT" 
		AND "MD_PATIENT"."PARTNER" = "=A0"."BUSINESSPARTNER" )
),"/CMSBE/INVTYPT" AS (SELECT
	 "INVTYPTEXT"."MANDT" AS "MANDT",
	 "INVTYPTEXT"."INV_TYPE" AS "INVTYPE",
	 "INVTYPTEXT"."SPRAS" AS "LANGUAGE",
	 "INVTYPTEXT"."INV_TYPE_DESC" AS "INVTYPEDESC" 
	FROM "SAPHANADB"."/CMSBE/CT_015T" "INVTYPTEXT" 
	WHERE "INVTYPTEXT"."SPRAS" = 'S' 
), "/CMSBE/INVTYP" AS (SELECT
	 "INVTYP"."MANDT" AS "MANDT",
	 "INVTYP"."INV_TYPE",
	 "=A0"."INVTYPEDESC",
	 "INVTYP"."COLLECTIVE" AS "COLLECTIVE",
	 "INVTYP"."INV_CLASS" 
	FROM "SAPHANADB"."/CMSBE/CT_015" "INVTYP" 
	LEFT OUTER MANY TO ONE JOIN "/CMSBE/INVTYPT" "=A0" ON ( "INVTYP"."MANDT" = "=A0"."MANDT" 
		AND "INVTYP"."INV_TYPE" = "=A0"."INVTYPE" )	
), "/CMSBE/I_DM_PARTNER_TYPE" as (SELECT
	 RTRIM( 
		LEFT( RTRIM( "DD07T"."DOMVALUE_L" ),
	 3 )) AS "PARTNERTYPE",
	 "DD07T"."DDTEXT" AS "PARTNERTYPEDESC",
	 "DD07T"."DDLANGUAGE"
	FROM "SAPHANADB"."DD07T" "DD07T" 
	WHERE ( "DD07T"."DOMNAME" = N'/CMSBE/PARTNER_TYPE' 
		AND "DD07T"."DDLANGUAGE" = 'S')
), "/CMSBE/DM_INV_CANC_STATUST" as (SELECT
	 "DD07T"."DDLANGUAGE" AS "LANGUAGE",
	 RTRIM( 
		LEFT( RTRIM( "DD07T"."DOMVALUE_L" ),
	 1 )) AS "CANCELSTATUS",
	 "DD07T"."DDTEXT" AS "CANCELSTATUSTEXT" 
	FROM "SAPHANADB"."DD07T" "DD07T" 
	WHERE ( "DD07T"."DOMNAME" = N'/CMSBE/INV_CANC_STATUS' 
		AND "DD07T"."AS4LOCAL" = N'A' AND "DD07T"."DDLANGUAGE" = 'S')

), "/CMSBE/TDSRV" AS (SELECT
	 "TD_SERVICES"."MANDT" AS "MANDT",
	 "TD_SERVICES"."DB_KEY" AS "DBKEY",
	 "TD_SERVICES"."HOST_KEY" AS "HOSTKEY",
	 "TD_SERVICES"."SRV_UNIQ_ID" AS "SRVUNIQID",
	 "TD_SERVICES"."MD_SERVICE_KEY" AS "MDSERVICEKEY",
	 "TD_SERVICES"."MD_BILLSRV_KEY" AS "MDBILLSRVKEY",
	 "TD_SERVICES"."QUANTITY" AS "QUANTITY",
	 "TD_SERVICES"."UNIT" AS "UNIT",
	 "TD_SERVICES"."SRV_DATE" AS "SRVDATE",
	 "TD_SERVICES"."SRV_TIME" AS "SRVTIME",
	 "TD_SERVICES"."BILLABLE" AS "BILLABLE",
	 "TD_SERVICES"."MAN_PRICE" AS "MANPRICE",
	 "TD_SERVICES"."PRICE_CURR" AS "PRICECURR",
	 "TD_SERVICES"."MAN_SRV_TEXT" AS "MANSRVTEXT",
	 "TD_SERVICES"."BASE_PRICE" AS "BASEPRICE",
	 "TD_SERVICES"."TOTAL_PRICE" AS "TOTALPRICE",
	 "TD_SERVICES"."SERVICE_COST" AS "SERVICECOST",
	 "TD_SERVICES"."KNUMV" AS "KNUMV",
	 "TD_SERVICES"."SOURCE_CONTEXT" AS "SOURCECONTEXT",
	 "TD_SERVICES"."MAIN_PAYOR" AS "MAINPAYOR",
	 "TD_SERVICES"."MAIN_PAYOR_TYPE" AS "MAINPAYORTYPE",
	 "TD_SERVICES"."TIMESLOT" AS "TIMESLOT",
	 "TD_SERVICES"."RANK" AS "RANK",
	 "TD_SERVICES"."SRV_STATUS" AS "SRVSTATUS" 
	FROM "SAPHANADB"."/CMSBE/TDSERVICE" "TD_SERVICES"
), "/CMSBE/MD_INSPROV_CLASS" AS(SELECT
	 "CLASS"."MANDT" AS "MANDT",
	 "CLASS"."INSPRV_TYPE" AS "INSPRVCLASS",
	 "TEXTCLASS"."INSPRV_TYPE_DESC" AS "INSPRVCLASSTEXT"
	FROM "SAPHANADB"."/CMSBE/CT_006" "CLASS" 
	INNER JOIN "SAPHANADB"."/CMSBE/CT_006T" "TEXTCLASS" ON ( "CLASS"."MANDT" = "TEXTCLASS"."MANDT" 
		AND "CLASS"."INSPRV_TYPE" = "TEXTCLASS"."INSPRV_TYPE" ) 
	WHERE ( "CLASS"."MANDT" = 100 AND "TEXTCLASS"."SPRAS" = 'S' )
), "/CMSBE/CT_INSPRV_CLASS_TYPET" AS (SELECT
	 "/CMSBE/CT_006T"."MANDT" AS "MANDT",
	 "/CMSBE/CT_006T"."SPRAS" AS "LANGUAGE",
	 "/CMSBE/CT_006T"."INSPRV_TYPE" AS "INSPRVCLASSTYPE",
	 "/CMSBE/CT_006T"."INSPRV_TYPE_DESC" AS "INSPRVCLASSTYPEDESC" 
	FROM "SAPHANADB"."/CMSBE/CT_006T" "/CMSBE/CT_006T" 
	WHERE ( "/CMSBE/CT_006T"."MANDT" = 100)
		AND "/CMSBE/CT_006T"."SPRAS" = 'S' 
), "/CMSBE/MDINSP" AS (SELECT
	 "MD_INSPROV"."MANDT" AS "MANDT",
	 "MD_INSPROV"."DB_KEY" AS "DBKEY",
	 "MD_INSPROV"."INSPRV_KEY" AS "INSPRVKEY",
	 "MD_INSPROV"."INSPRV_BP" AS "INSPRVBP",
	 "MD_INSPROV"."INSPROV_TYPE" AS "INSPRVCLASS",
	 "=A0"."INSPRVCLASSTYPEDESC" AS "INSPRVCLASSTYPEDESC",
	 CASE "=A1"."ADDITIONALLASTNAME" WHEN N'' 
	THEN "=A1"."BUSINESSPARTNERFULLNAME" 
	ELSE ( RTRIM( RTRIM ( "=A1"."BUSINESSPARTNERFULLNAME" ) || RPAD( '',
	 1,
	 NCHAR( 32) ) || RTRIM ( "=A1"."ADDITIONALLASTNAME" ) ) ) 
	END AS "BUSINESSPARTNERFULLNAME" 
	FROM ( "SAPHANADB"."/CMSBE/MDINSPROV" "MD_INSPROV" 
		LEFT OUTER MANY TO ONE JOIN "/CMSBE/CT_INSPRV_CLASS_TYPET" "=A0" ON ( "MD_INSPROV"."MANDT" = "=A0"."MANDT" 
			AND "MD_INSPROV"."INSPROV_TYPE" = "=A0"."INSPRVCLASSTYPE" ) ) 
	LEFT OUTER MANY TO ONE JOIN IBUSINESSPARTNER_VIEW "=A1" ON ( "MD_INSPROV"."MANDT" = "=A1"."MANDT" 
		AND "MD_INSPROV"."INSPRV_BP" = "=A1"."BUSINESSPARTNER" )
), "/CMSBE/SRVTYP1" AS (SELECT
	 "SERVICETYPE1"."MANDT" AS "MANDT",
	 "SERVICETYPE1"."SERV_TYPE_01" AS "SRVTYP1_ID" 
	FROM "SAPHANADB"."/CMSBE/CT_004" "SERVICETYPE1"	
), "/CMSBE/SRVTYP1T" AS (SELECT
	 "SERVICETYPE1TEXT"."MANDT" AS "MANDT",
	 "SERVICETYPE1TEXT"."SPRAS" AS "LANGUAGE",
	 "SERVICETYPE1TEXT"."SERV_TYPE_01" AS "SRVTYP1_ID",
	 "SERVICETYPE1TEXT"."SRV_TYP_DESC" AS "SRVTYP1DESC" 
	FROM "SAPHANADB"."/CMSBE/CT_004T" "SERVICETYPE1TEXT" 
	WHERE "SERVICETYPE1TEXT"."SPRAS" = 'S' 
), "/CMSBE/SRVTYP2" AS (SELECT
	 "SERVICETYPE2"."MANDT" AS "MANDT",
	 "SERVICETYPE2"."SERV_TYPE_02" AS "SRVTYP2_ID" 
	FROM "SAPHANADB"."/CMSBE/CT_005" "SERVICETYPE2"
), "/CMSBE/SRVTYP2T" AS (SELECT
	 "SERVICETYPE2TEXT"."MANDT" AS "MANDT",
	 "SERVICETYPE2TEXT"."SERV_TYPE_02" AS "SRVTYP2_ID",
	 "SERVICETYPE2TEXT"."SPRAS" AS "LANGUAGE",
	 "SERVICETYPE2TEXT"."SRV_TYP_DESC" AS "SRVTYP2DESC" 
	FROM "SAPHANADB"."/CMSBE/CT_005T" "SERVICETYPE2TEXT" 
	WHERE "SERVICETYPE2TEXT"."SPRAS" = 'S'
),"/CMSBE/MDSRV" AS (SELECT
	 "MD_SERVICE"."MANDT" AS "MANDT",
	 "MD_SERVICE"."DB_KEY" AS "DBKEY",
	 "MD_SERVICE"."SRV_CAT" AS "SRVCATALOG",
	 "MD_SERVICE"."SRV_ID" AS "SRVID",
	 "MD_SERVICE"."SRV_RELEASED" AS "SRVRELEASED",
	 "MD_SERVICE"."SRV_CATEGORY" AS "SRVCATEGORY",
	 "MD_SERVICE"."SRV_TYP" AS "SRVTYP1",
	 "MD_SERVICE"."SRV_TYP_2" AS "SRVTYP2",
	 "MD_SERVICE"."SRV_PACKAGE" AS "PKG",
	 "MD_SERVICE"."TAX_IND" AS "TAXIND",
	 "MD_SERVICE"."DIV_TEXT" AS "DIVTEXT",
	 "MD_SERVICE"."SRV_MAN_PRICE" AS "MANPRICE",
	 "MD_SERVICE"."SRV_UNIT" AS "UNIT",
	 "MD_SERVICE"."SRV_BLOCK_TO" AS "SRVBLOCKTO",
	 "MD_SERVICE"."SRV_BLOCK_FROM" AS "SRVBLOCKFROM" 
	FROM "SAPHANADB"."/CMSBE/MDSERVICE" "MD_SERVICE"
), "/CMSBE/MDSRVT" AS (SELECT
	 "MD_SRV_TEXT"."MANDT" AS "MANDT",
	 "MD_SRV_TEXT"."PARENT_KEY" AS "PARENTKEY",
	 "MD_SRV_TEXT"."SPRAS" AS "LANGUAGE",
	 "MD_SRV_TEXT"."SRV_TXT" AS "SRVTXT" 
	FROM "SAPHANADB"."/CMSBE/MDSERVTXT" "MD_SRV_TEXT" 
	WHERE "MD_SRV_TEXT"."SPRAS" = 'S'
), "/CMSBE/I_DM_PLAN_DISC" AS (SELECT
	 RTRIM( 
		LEFT( RTRIM( "DD07T"."DOMVALUE_L" ),
	 1 )) AS "PLANDISC",
	 "DD07T"."DDTEXT" AS "PLANDISCDESC" 
	FROM "SAPHANADB"."DD07T" "DD07T" 
	WHERE ( "DD07T"."DOMNAME" = N'/CMSBE/DISCH_STAT' 
		AND "DD07T"."DDLANGUAGE" = 'S' )
), "/CMSBE/TDEP" AS(SELECT
	 "TD_EP"."MANDT" AS "MANDT",
	 "TD_EP"."DB_KEY" AS "DBKEY",
	 "TD_EP"."INST" AS "INST",
	 "TD_EP"."EP_ID" AS "EPID",
	 "TD_EP"."MD_PATIENT_KEY" AS "MDPATIENTKEY",
	 "TD_EP"."CASE_TYPE" AS "CASETYPE",
	 "TD_EP"."CASE_CLASSIF" AS "CASECLASSIF",
	 "TD_EP"."ADM_DATE" AS "ADMDATE",
	 "TD_EP"."ADM_TIME" AS "ADMTIME",
	 "TD_EP"."END_DATE" AS "ENDDATE",
	 "TD_EP"."END_TIME" AS "ENDTIME",
	 "TD_EP"."BILL_STATE" AS "BILLSTATE",
	 "TD_EP"."PLAN_DISC" AS "PLANDISC",
	 "TD_EP"."CASE_ISSUE" AS "CASEISSUE",
	 "TD_EP"."REL_CASE" AS "RELATEDCASE",
	 "TD_EP"."REL_TYPE" AS "RELATEDTYPE",
	 "TD_EP"."PROCESS_STATUS" AS "PROCESSSTATUS",
	 "TD_EP"."CO_ORDER" AS "INTERNALORDER",
	 "TD_EP"."ALOS" AS "ALOS",
	 "TD_EP"."ELOS" AS "ELOS",
	 RTRIM( CAST( CONCAT( RTRIM ( CONCAT( N'ZE' ,
	 RTRIM ( "TD_EP"."INST" ) ) ) ,
	 RTRIM ( "TD_EP"."EP_ID" ) ) AS NVARCHAR( 000022) ) ) AS "OBJNR",
	 N'ZBE' AS "OBJECTTYPE",
	 CASE "TD_EP"."CASE_TYPE" WHEN N'2' 
	THEN N'' WHEN N'3' 
	THEN N'' 
	ELSE "=A0"."PLANDISCDESC" 
	END AS "FORMATPLANDISCDESC",
	 "TD_EP"."BILL_STATE_REASON" AS "BILLSTATEREASON" 
	FROM "SAPHANADB"."/CMSBE/TDEPISODE" "TD_EP" 
	LEFT OUTER MANY TO ONE JOIN "/CMSBE/I_DM_PLAN_DISC" "=A0" ON "TD_EP"."PLAN_DISC" = "=A0"."PLANDISC"
), "/CMSBE/MDBUSP_V" AS (SELECT
	 "/CMSBE/MDBUSP"."MANDT" AS "MANDT",
	 "/CMSBE/MDBUSP"."DB_KEY" AS "DBKEY",
	 "/CMSBE/MDBUSP"."BP_ID" AS "BPID",
	 "/CMSBE/MDBUSP"."BU_PARTNER" AS "BUPARTNER",
	 "=A0"."FORMOFADDRESS" AS "TREATMENT",
	 CASE WHEN NOT ( "=A0"."ADDITIONALLASTNAME" = N'' ) 
	THEN "=A0"."BUSINESSPARTNERFULLNAME" 
	ELSE ( RTRIM( RTRIM ( "=A0"."BUSINESSPARTNERFULLNAME" ) || RPAD( '',1, NCHAR( 32) ) || RTRIM ( "=A0"."ADDITIONALLASTNAME" ) ) ) 
	END AS "BUSINESSPARTNERFULLNAME",
	 "=A0"."LASTNAME" AS "LASTNAME" 
	FROM "SAPHANADB"."/CMSBE/MDBUSP" "/CMSBE/MDBUSP" 
	LEFT OUTER MANY TO ONE JOIN IBUSINESSPARTNER_VIEW "=A0" ON ( "/CMSBE/MDBUSP"."MANDT" = "=A0"."MANDT" 
		AND "/CMSBE/MDBUSP"."BU_PARTNER" = "=A0"."BUSINESSPARTNER" )
), "/CMSBE/TDBUSPV" AS (SELECT
	 "/CMSBE/TDBUSP"."MANDT" AS "MANDT",
	 "/CMSBE/TDBUSP"."DB_KEY" AS "DBKEY",
	 "/CMSBE/TDBUSP"."HOST_BO_KEY" AS "HOSTBOKEY",
	 "/CMSBE/TDBUSP"."HOST_NODE_KEY" AS "HOSTNODEKEY",
	 "/CMSBE/TDBUSP"."HOST_KEY" AS "HOSTKEY",
	 "/CMSBE/TDBUSP"."MD_BUSP_KEY" AS "MDBUSPKEY",
	 "/CMSBE/TDBUSP"."BP_ROLE" AS "BPROLE",
	 "/CMSBE/TDBUSP"."CREA_DATE_TIME" AS "CREADATETIME",
	 "/CMSBE/TDBUSP"."CREA_UNAME" AS "CREAUNAME",
	 "/CMSBE/TDBUSP"."LCHG_DATE_TIME" AS "LCHGDATETIME",
	 "/CMSBE/TDBUSP"."LCHG_UNAME" AS "LCHGUNAME",
	 "=A0"."BPID" AS "BPID",
	 "=A0"."BUPARTNER" AS "BUPARTNER" 
	FROM "SAPHANADB"."/CMSBE/TDBUSP" "/CMSBE/TDBUSP" 
	LEFT OUTER MANY TO ONE JOIN "/CMSBE/MDBUSP_V" "=A0" ON ( "/CMSBE/TDBUSP"."MANDT" = "=A0"."MANDT" 
		AND "/CMSBE/TDBUSP"."MD_BUSP_KEY" = "=A0"."DBKEY" )
),"ICALENDARDATE" AS (SELECT
	 "SCAL_TT_DATE"."CALENDARDATE" AS "CALENDARDATE",
	 "SCAL_TT_DATE"."CALENDARYEAR" AS "CALENDARYEAR",
	 "SCAL_TT_DATE"."CALENDARQUARTER" AS "CALENDARQUARTER",
	 "SCAL_TT_DATE"."CALENDARMONTH" AS "CALENDARMONTH",
	 "SCAL_TT_DATE"."CALENDARWEEK" AS "CALENDARWEEK",
	 "SCAL_TT_DATE"."CALENDARDAY" AS "CALENDARDAY",
	 "SCAL_TT_DATE"."YEARMONTH" AS "YEARMONTH",
	 "SCAL_TT_DATE"."YEARQUARTER" AS "YEARQUARTER",
	 "SCAL_TT_DATE"."YEARWEEK" AS "YEARWEEK",
	 "SCAL_TT_DATE"."WEEKDAY" AS "WEEKDAY",
	 "SCAL_TT_DATE"."FIRSTDAYOFWEEKDATE" AS "FIRSTDAYOFWEEKDATE",
	 "SCAL_TT_DATE"."FIRSTDAYOFMONTHDATE" AS "FIRSTDAYOFMONTHDATE",
	 "SCAL_TT_DATE"."CALENDARDAYOFYEAR" AS "CALENDARDAYOFYEAR",
	 "SCAL_TT_DATE"."YEARDAY" AS "YEARDAY" 
	FROM "SAPHANADB"."SCAL_TT_DATE" "SCAL_TT_DATE"
), "ZRCM_REPORT01" AS (SELECT "/CMSBE/REPORT_01"."MANDT" AS "MANDT",
	 "/CMSBE/REPORT_01"."INVOICE_KEY" AS "INVOICEKEY",
	 "/CMSBE/REPORT_01"."INVOICEPOS_BASE_AMOUNT" AS "INVOICEPOSBASEAMOUNT",
	 "/CMSBE/REPORT_01"."INVOICE_PARTNER_TYPE" AS "INVOICEPARTNERTYPE",
	 "/CMSBE/REPORT_01"."SERVICEMD_CAT" AS "SERVICEMDCAT",
	 "/CMSBE/REPORT_01"."SERVICEMD_ID" AS "SERVICEMDID",
	 "/CMSBE/REPORT_01"."EPISODE_INST" AS "EPISODEINST"
FROM "SAPHANADB"."/CMSBE/REPORT_01" "/CMSBE/REPORT_01" 
WHERE "/CMSBE/REPORT_01"."MANDT" = 100
), "ZRCM_AUDPRES_CAL" AS (SELECT 
	 "ZRCM_REPORT01"."MANDT" AS "MANDT",
	 "ZRCM_REPORT01"."INVOICEKEY",
	 "=A0"."DISCOUNT_TYPE" AS "DISCOUNTTYPE",
	 SUM( "ZRCM_REPORT01"."INVOICEPOSBASEAMOUNT" ) AS "TOTAL"
FROM "ZRCM_REPORT01" "ZRCM_REPORT01"
LEFT OUTER MANY TO MANY JOIN "SAPHANADB"."ZAUNA_CT_AUD_PRE" "=A0" ON ( "ZRCM_REPORT01"."INVOICEPARTNERTYPE" = "=A0"."PARTNER_TYPE" 
		AND "ZRCM_REPORT01"."EPISODEINST" = "=A0"."INST" 
		AND "ZRCM_REPORT01"."SERVICEMDCAT" = "=A0"."SRV_CAT" 
		AND "ZRCM_REPORT01"."SERVICEMDID" = "=A0"."SRV_ID" 
		AND "=A0"."ACTIV" = N'X' 
		AND "ZRCM_REPORT01"."MANDT" = "=A0"."MANDT" ) 
GROUP BY "ZRCM_REPORT01"."MANDT", "ZRCM_REPORT01"."INVOICEKEY", "=A0"."DISCOUNT_TYPE"
),"ZRCM_PRCD_ELEM" AS (SELECT
	 "/CMSBE/REPORT_01"."MANDT" AS "MANDT",
	 "/CMSBE/REPORT_01"."INVOICE_KEY" AS "INVOICEKEY",
	 "=A0"."KSCHL" AS "KSCHL",
	 SUM( "=A0"."KWERT" ) AS "KWERT" 
	FROM "SAPHANADB"."/CMSBE/REPORT_01" "/CMSBE/REPORT_01" 
	LEFT OUTER MANY TO MANY JOIN "SAPHANADB"."PRCD_ELEMENTS" "=A0" ON ( "/CMSBE/REPORT_01"."MANDT" = "=A0"."CLIENT" 
		AND "/CMSBE/REPORT_01"."SERVICE_KNUMV" = "=A0"."KNUMV" ) 
	GROUP BY "/CMSBE/REPORT_01"."MANDT",
	 "/CMSBE/REPORT_01"."INVOICE_KEY",
	 "=A0"."KSCHL"
),"ZRCM_REP01_SUM" AS(SELECT
	 "/CMSBE/REPORT_01"."MANDT" AS "MANDT",
	 "/CMSBE/REPORT_01"."INVOICE_KEY" AS "INVOICEKEY",
	 SUM( "/CMSBE/REPORT_01"."INVOICEPOS_KZWI2" ) AS "DESCUENTOCONVENIO",
	 SUM( "/CMSBE/REPORT_01"."INVOICEPOS_KZWI4" ) AS "DESCUENTOEPISODIO",
	 SUM( "/CMSBE/REPORT_01"."INVOICEPOS_BASE_AMOUNT" ) AS "SUBTOTALFACTURA",
	 SUM( "/CMSBE/REPORT_01"."INVOICEPOS_TOTAL_AMOUNT" ) AS "TOTALFACTURA" 
	FROM "SAPHANADB"."/CMSBE/REPORT_01" "/CMSBE/REPORT_01" 
	GROUP BY "/CMSBE/REPORT_01"."MANDT",
	 "/CMSBE/REPORT_01"."INVOICE_KEY"
)SELECT
"/CMSBE/REPORT_01"."EPISODE_INST" AS "Centro Sanitario",
"=A15"."CASETYPEDESC" AS "Tipo Paciente",
"/CMSBE/REPORT_01"."PATIENT_ID" AS "No. HC",
"/CMSBE/REPORT_01"."EPISODE_ID" AS "Episodio",
--"/CMSBE/REPORT_01"."PATIEND_BP" AS "PATIENDBP",
"=A21"."BUSINESSPARTNERFULLNAME" AS "PACIENTE",
"=A16"."ADMDATE" AS "FECHA_INGRESO",
CASE WHEN ( "=A16"."ENDDATE" IS NULL OR "=A16"."ENDDATE" = N'00000000' ) THEN N'' ELSE "=A16"."ENDDATE" END AS "FECHA_EGRESO",
"=A16"."ALOS" AS "Días Estancia",
N'' AS "Días Estancia UCI",
CASE "/CMSBE/REPORT_01"."INVOICE_PARTNER_TYPE" WHEN N'PAT' THEN N'-' WHEN N'INS' THEN "/CMSBE/REPORT_01"."COVERAGE_INSPRV_BP" ELSE N'' END AS "Pagador",
CASE "/CMSBE/REPORT_01"."INVOICE_PARTNER_TYPE" WHEN N'PAT' THEN N'' ELSE "=A5"."BUSINESSPARTNERFULLNAME" END AS "Nombre Pagador",
CASE "/CMSBE/REPORT_01"."INVOICE_PARTNER_TYPE" WHEN N'INS' 
	THEN N'ASEGURADORA' WHEN N'AGG' 
	THEN N'GRUPO ASEGURADORAS' WHEN N'PAT' 
	THEN N'PARTICULAR' ELSE N'' END AS "Tipo Pagador",
CASE "=A19"."BPROLE" WHEN N'' THEN "=A17"."BPROLE" ELSE "=A19"."BPROLE" END AS "Esp. Médico Intern.",
CASE "/CMSBE/REPORT_01"."SERVICE_ORUN_DP_ID" WHEN N'' THEN "/CMSBE/REPORT_01"."MOVEMENT_ORUN_DP_ID" ELSE "/CMSBE/REPORT_01"."SERVICE_ORUN_DP_ID" END AS "Departamento",
"=A24"."ORGUN_TEXT" AS "Nombre Departamento",
"/CMSBE/REPORT_01"."SERVICE_ID" AS "ID Único Prest.",
"/CMSBE/REPORT_01"."SERVICEMD_ID" AS "Prestación",
"=A13"."SRVTXT" AS "Desc. Prestación",
"/CMSBE/REPORT_01"."SERVICE_QUANTITY" AS "Cant. Cargo",
CAST( N'0' AS DECIMAL(000010,	000002) ) AS "Cant. inc. Paquete",
"/CMSBE/REPORT_01"."INVOICEPOS_TOTAL_AMOUNT" AS "Total de la Prestación",
"/CMSBE/REPORT_01"."SERVICEMD_TYP" AS "Tipo Prestación Principal",
"=A8"."SRVTYP1DESC" AS "Descripción del Prestación Principal",
"/CMSBE/REPORT_01"."SERVICEMD_TYP_2" AS "Tipo Prestación Secundaria",
"=A10"."SRVTYP2DESC" AS "Descripción del Prestación Secundaria",
"/CMSBE/REPORT_01"."SERVICEMD_CATEGORY" AS "Categoría",
"=A6"."SRV_CAT_DESC" AS "Descripción de la categoría",
"=A11"."SRV_CONV_ID" AS "Código de Conversión",
"/CMSBE/REPORT_01"."SERVICE_COST" AS "Costo Unit. Cargo",
CAST( CAST( ( CAST ( CAST( "/CMSBE/REPORT_01"."SERVICE_BASE_PRICE" AS DECIMAL(000013,000002) ) AS DECIMAL ) / "=A3"."QUANTITY") AS DECIMAL ) AS DECIMAL(000013,000002) ) AS "Precio Unitario",
"/CMSBE/REPORT_01"."INVOICEPOS_TAX_AMOUNT" AS "IVA de la prestación",
CASE "/CMSBE/REPORT_01"."SERVICE_ORUN_OU_ID" WHEN N'' THEN "/CMSBE/REPORT_01"."MOVEMENT_ORUN_OU_ID" ELSE "/CMSBE/REPORT_01"."SERVICE_ORUN_OU_ID" END AS "Unidad Org",
"=A26"."ORGUN_TEXT" AS "Descripción de unidad org.",
"=A27"."CALENDARWEEK" AS "Semana Cargo",
"=A27"."CALENDARMONTH" AS "Mes Cargo",
"=A27"."CALENDARYEAR" AS "Año Cargo",
"/CMSBE/REPORT_01"."INVOICEPOS_BASE_AMOUNT" AS "Subtotal Cargo con Desc.",
CAST( "/CMSBE/REPORT_01"."INVOICEPOS_BASE_AMOUNT" AS DECIMAL(000013,000002) ) AS "SubTotal Prestación",
--"/CMSBE/REPORT_01"."SERVICE_BASE_PRICE" AS "SubTotal Prestación",
CASE "/CMSBE/REPORT_01"."EPISODE_CASE_TYPE" WHEN N'1' THEN N'Hospitalización' ELSE N'Otros' END AS "Tipo Admisión",
--"=A15"."CASETYPEDESC" AS "Tipo Admisión",
"=A3"."SRVDATE" AS "Fecha Cargo",
CAST( CAST( ("/CMSBE/REPORT_01"."INVOICEPOS_BASE_AMOUNT" - CAST( ("/CMSBE/REPORT_01"."INVOICEPOS_KZWI2" + "/CMSBE/REPORT_01"."INVOICEPOS_KZWI4") AS DECIMAL(000014,000002) )) AS DECIMAL(000015,000002) ) AS DECIMAL(000013,000002) ) AS "Subtotal Cargo sin Desc.",
"/CMSBE/REPORT_01"."INVOICE_NUMBER" AS "Factura",
"/CMSBE/REPORT_01"."INVOICEPOS_ID" AS "Pos. Factura",
CAST( "=A28"."TOTAL" AS DECIMAL(000013,000002) ) AS "Deducible",
CAST( "=A29"."TOTAL" AS DECIMAL(000013,000002) ) AS "Deducible Adicional",
CAST( "=A30"."TOTAL" AS DECIMAL(000013,000002) ) AS "CoaSeguro",
CAST( "=A31"."TOTAL" AS DECIMAL(000013,000002) ) AS "CoaSeguro Honorarios",
CAST( "=A32"."TOTAL" AS DECIMAL(000013,000002) ) AS "Copago",
CAST( "=A33"."KWERT" AS DECIMAL(000013,000002) ) AS "Subtotal Factura AD",
CAST( "=A34"."KWERT" AS DECIMAL(000013,000002) ) AS "IVA de la factura AD",
CAST( "=A35"."KWERT" AS DECIMAL(000013,000002) ) AS "Total Factura AD",
CAST( "=A36"."DESCUENTOCONVENIO" AS DECIMAL(000013,000002) ) AS "Descuentos de Convenio",
CAST( "=A37"."KWERT" AS DECIMAL(000013,000002) ) AS "Descuento por Episodio",
CAST( "=A38"."TOTAL" AS DECIMAL(000013,000002) ) AS "Descuento Catastrófico",
CAST( "=A39"."TOTAL" AS DECIMAL(000013,000002) ) AS "Descuento Ajuste Catastrófico",
CAST( "=A40"."TOTAL" AS DECIMAL(000013,000002) ) AS "Descuento Ajuste x Facultamiento",
CAST( CAST( (CAST( (CAST( ("=A36"."DESCUENTOCONVENIO" + "=A36"."DESCUENTOEPISODIO") AS DECIMAL(000014,000002) ) + "=A40"."TOTAL") AS DECIMAL(000015,000002) ) + "=A39"."TOTAL") AS DECIMAL(000016,000002) ) AS DECIMAL(000013,000002) ) AS "Importe Total Descuentos",
CAST( "=A36"."SUBTOTALFACTURA" AS DECIMAL(000013,000002) ) AS "Subtotal Factura",
CAST( "=A41"."KWERT" AS DECIMAL(000013,000002) ) AS "IVA factura",
CAST( "=A36"."TOTALFACTURA" AS DECIMAL(000013,000002) ) AS "Total factura",
"=A22"."XBLNR" AS "Fact. Fiscal",
"/CMSBE/REPORT_01"."INVOICE_DATE" AS "Fecha Factura",
"/CMSBE/REPORT_01"."INVOICE_FI_BELNR" AS "Doc. Financiero",
"/CMSBE/REPORT_01"."INVOICE_FI_GJAHR" AS "Año Doc. FI",
"/CMSBE/REPORT_01"."INVOICE_FI_BELNR" AS "Sociedad Doc. FI",
CASE "=A19"."BPID" WHEN N'' THEN "=A17"."BPID" ELSE "=A19"."BPID" END AS "ID Médico Tratamiento",
CASE "=A20"."BUSINESSPARTNERFULLNAME" WHEN N'' THEN "=A18"."BUSINESSPARTNERFULLNAME" ELSE "=A20"."BUSINESSPARTNERFULLNAME" END AS "Nombre Médico Tratamiento",
"=A17"."BPID" AS "ID Médico Admisión",
"=A18"."BUSINESSPARTNERFULLNAME" AS "Nombre Médico Admisión",
"=A2"."CANCELSTATUSTEXT" AS "Estado Cancelación Factura",
"=A0"."INVTYPEDESC" AS "Nombre Tipo Factura",
N'' AS "ID Broker",
N'' AS "Nombre Broker",
N'' AS "ID Compañia",
N'' AS "Nombre Compañía" 
FROM "SAPHANADB"."/CMSBE/REPORT_01" "/CMSBE/REPORT_01"
LEFT OUTER MANY TO ONE JOIN "/CMSBE/INVTYP" "=A0" ON ( "/CMSBE/REPORT_01"."MANDT" = "=A0"."MANDT" AND "/CMSBE/REPORT_01"."INVOICE_TYPE" = "=A0"."INV_TYPE" ) 
LEFT OUTER MANY TO ONE JOIN "/CMSBE/I_DM_PARTNER_TYPE" "=A1" ON "/CMSBE/REPORT_01"."INVOICE_PARTNER_TYPE" = "=A1"."PARTNERTYPE"  
LEFT OUTER MANY TO ONE JOIN "/CMSBE/DM_INV_CANC_STATUST" "=A2" ON "/CMSBE/REPORT_01"."INVOICE_CANCEL_STATUS" = "=A2"."CANCELSTATUS"  
LEFT OUTER MANY TO ONE JOIN "/CMSBE/TDSRV" "=A3" ON ( "/CMSBE/REPORT_01"."MANDT" = "=A3"."MANDT" AND "/CMSBE/REPORT_01"."SERVICE_KEY" = "=A3"."DBKEY" ) 
LEFT OUTER MANY TO ONE JOIN "/CMSBE/MD_INSPROV_CLASS" "=A4" ON ( "/CMSBE/REPORT_01"."MANDT" = "=A4"."MANDT" AND "/CMSBE/REPORT_01"."COVERAGE_INSPRV_TYP" = "=A4"."INSPRVCLASS" )  
LEFT OUTER MANY TO ONE JOIN "/CMSBE/MDINSP" "=A5" ON ( "/CMSBE/REPORT_01"."COVERAGE_INSPRV_ID" = "=A5"."INSPRVKEY" AND "/CMSBE/REPORT_01"."COVERAGE_INSPRV_BP" = "=A5"."INSPRVBP" AND "/CMSBE/REPORT_01"."MANDT" = "=A5"."MANDT" ) 
LEFT OUTER MANY TO ONE JOIN "SAPHANADB"."/CMSBE/CT_027T" "=A6" ON ( "/CMSBE/REPORT_01"."SERVICEMD_CATEGORY" = "=A6"."SRV_CAT" AND "=A6"."SPRAS" = 'S' AND "/CMSBE/REPORT_01"."MANDT" = "=A6"."MANDT" )  --ESPAÑOL
LEFT OUTER MANY TO ONE JOIN "/CMSBE/SRVTYP1" "=A7" ON ( "/CMSBE/REPORT_01"."MANDT" = "=A7"."MANDT" AND "/CMSBE/REPORT_01"."SERVICEMD_TYP" = "=A7"."SRVTYP1_ID" ) 
LEFT OUTER MANY TO ONE JOIN "/CMSBE/SRVTYP1T" "=A8" ON ( "/CMSBE/REPORT_01"."MANDT" = "=A8"."MANDT" AND "=A7"."SRVTYP1_ID" = "=A8"."SRVTYP1_ID" ) 
LEFT OUTER MANY TO ONE JOIN "/CMSBE/SRVTYP2" "=A9" ON ( "/CMSBE/REPORT_01"."MANDT" = "=A9"."MANDT" AND "/CMSBE/REPORT_01"."SERVICEMD_TYP_2" = "=A9"."SRVTYP2_ID" ) 
LEFT OUTER MANY TO ONE JOIN "/CMSBE/SRVTYP2T" "=A10" ON ( "/CMSBE/REPORT_01"."MANDT" = "=A10"."MANDT" AND "=A9"."SRVTYP2_ID" = "=A10"."SRVTYP2_ID" ) 
LEFT OUTER MANY TO ONE JOIN "SAPHANADB"."/CMSBE/MDSERVCNV" "=A11" ON ( "/CMSBE/REPORT_01"."MANDT" = "=A11"."MANDT" AND "/CMSBE/REPORT_01"."SERVICEMD_KEY" = "=A11"."PARENT_KEY" ) 
LEFT OUTER MANY TO ONE JOIN "/CMSBE/MDSRV" "=A12" ON ( "/CMSBE/REPORT_01"."MANDT" = "=A12"."MANDT" AND "/CMSBE/REPORT_01"."SERVICEMD_KEY" = "=A12"."DBKEY" ) 
LEFT OUTER MANY TO ONE JOIN "/CMSBE/MDSRVT" "=A13" ON ( "/CMSBE/REPORT_01"."MANDT" = "=A13"."MANDT" AND "=A12"."DBKEY" = "=A13"."PARENTKEY" ) 
LEFT OUTER MANY TO ONE JOIN "/CMSBE/EPTYP" "=A14" ON ( "/CMSBE/REPORT_01"."MANDT" = "=A14"."MANDT" AND "/CMSBE/REPORT_01"."EPISODE_CASE_TYPE" = "=A14"."CASETYPE" ) 
LEFT OUTER MANY TO ONE JOIN "/CMSBE/EPTYPT" "=A15" ON ( "/CMSBE/REPORT_01"."MANDT" = "=A15"."MANDT" AND "=A14"."CASETYPE" = "=A15"."CASETYPE" ) 
LEFT OUTER MANY TO ONE JOIN "/CMSBE/TDEP" "=A16" ON ( "/CMSBE/REPORT_01"."MANDT" = "=A16"."MANDT" AND "/CMSBE/REPORT_01"."EPISODE_KEY" = "=A16"."DBKEY") 
LEFT OUTER MANY TO ONE JOIN "/CMSBE/TDBUSPV" "=A17" ON ( "/CMSBE/REPORT_01"."MOVEMENT_KEY" = "=A17"."HOSTKEY" AND "=A17"."BPROLE" = N'01' AND "/CMSBE/REPORT_01"."MANDT" = "=A17"."MANDT" ) 
LEFT OUTER MANY TO ONE JOIN "/CMSBE/MDBUSP_V" "=A18" ON ( "/CMSBE/REPORT_01"."MANDT" = "=A18"."MANDT" AND "=A17"."MDBUSPKEY" = "=A18"."DBKEY" ) 
LEFT OUTER MANY TO ONE JOIN "/CMSBE/TDBUSPV" "=A19" ON ( "/CMSBE/REPORT_01"."MOVEMENT_KEY" = "=A19"."HOSTKEY" AND "=A19"."BPROLE" = N'02' AND "/CMSBE/REPORT_01"."MANDT" = "=A19"."MANDT" ) 
LEFT OUTER MANY TO ONE JOIN "/CMSBE/MDBUSP_V" "=A20" ON ( "/CMSBE/REPORT_01"."MANDT" = "=A20"."MANDT" AND "=A19"."MDBUSPKEY" = "=A20"."DBKEY" )
LEFT OUTER MANY TO ONE JOIN "/CMSBE/MDPAT" "=A21" ON ( "/CMSBE/REPORT_01"."MANDT" = "=A21"."MANDT" AND "/CMSBE/REPORT_01"."PATIENT_KEY" = "=A21"."DBKEY" ) 
LEFT OUTER MANY TO ONE JOIN "SAPHANADB"."BKPF" "=A22" ON ( "/CMSBE/REPORT_01"."INVOICE_FI_BUKRS" = "=A22"."BUKRS" AND "/CMSBE/REPORT_01"."INVOICE_FI_BELNR" = "=A22"."BELNR" AND "/CMSBE/REPORT_01"."INVOICE_FI_GJAHR" = "=A22"."GJAHR" AND "/CMSBE/REPORT_01"."MANDT" = "=A22"."MANDT" )
LEFT OUTER MANY TO ONE JOIN "SAPHANADB"."/CMSBE/MDORUN" "=A23" ON ("/CMSBE/REPORT_01"."SERVICE_ORUN_DP_ID" = "=A23"."ORUN_ID" OR "/CMSBE/REPORT_01"."MOVEMENT_ORUN_DP_ID" = "=A23"."ORUN_ID" OR "/CMSBE/REPORT_01"."SERVICE_ORUN_DP_ID" = "=A23"."ORUN_ID")
--LEFT OUTER MANY TO ONE JOIN "SAPHANADB"."/CMSBE/MDORUN" "=A23" ON ("/CMSBE/REPORT_01"."SERVICE_ORUN_OU_ID" = "=A23"."ORUN_ID")
LEFT OUTER MANY TO ONE JOIN "SAPHANADB"."/CMSBE/MDORUNTXT" "=A24" ON ("=A23"."DB_KEY" = "=A24"."PARENT_KEY")
LEFT OUTER MANY TO ONE JOIN "SAPHANADB"."/CMSBE/MDORUN" "=A25" ON ("/CMSBE/REPORT_01"."SERVICE_ORUN_OU_ID" = "=A25"."ORUN_ID" OR "/CMSBE/REPORT_01"."MOVEMENT_ORUN_OU_ID" = "=A25"."ORUN_ID" OR "/CMSBE/REPORT_01"."SERVICE_ORUN_OU_ID" = "=A25"."ORUN_ID")
LEFT OUTER MANY TO ONE JOIN "SAPHANADB"."/CMSBE/MDORUNTXT" "=A26" ON ("=A25"."DB_KEY" = "=A26"."PARENT_KEY")
LEFT OUTER MANY TO ONE JOIN "ICALENDARDATE" "=A27" ON ("=A3"."SRVDATE" = "=A27"."CALENDARDATE" )
LEFT OUTER MANY TO ONE JOIN "ZRCM_AUDPRES_CAL" "=A28" ON ("/CMSBE/REPORT_01"."INVOICE_KEY" = "=A28"."INVOICEKEY" AND "=A28"."DISCOUNTTYPE" = N'01' AND "/CMSBE/REPORT_01"."MANDT" = "=A28"."MANDT" )   
LEFT OUTER MANY TO ONE JOIN "ZRCM_AUDPRES_CAL" "=A29" ON ("/CMSBE/REPORT_01"."INVOICE_KEY" = "=A29"."INVOICEKEY" AND "=A29"."DISCOUNTTYPE" = N'02' AND "/CMSBE/REPORT_01"."MANDT" = "=A29"."MANDT" ) 
LEFT OUTER MANY TO ONE JOIN "ZRCM_AUDPRES_CAL" "=A30" ON ("/CMSBE/REPORT_01"."INVOICE_KEY" = "=A30"."INVOICEKEY" AND "=A30"."DISCOUNTTYPE" = N'03' AND "/CMSBE/REPORT_01"."MANDT" = "=A30"."MANDT" )  
LEFT OUTER MANY TO ONE JOIN "ZRCM_AUDPRES_CAL" "=A31" ON ("/CMSBE/REPORT_01"."INVOICE_KEY" = "=A31"."INVOICEKEY" AND "=A31"."DISCOUNTTYPE" = N'05' AND "/CMSBE/REPORT_01"."MANDT" = "=A31"."MANDT" ) 
LEFT OUTER MANY TO ONE JOIN "ZRCM_AUDPRES_CAL" "=A32" ON ("/CMSBE/REPORT_01"."INVOICE_KEY" = "=A32"."INVOICEKEY" AND "=A32"."DISCOUNTTYPE" = N'04' AND "/CMSBE/REPORT_01"."MANDT" = "=A32"."MANDT" )  
LEFT OUTER MANY TO ONE JOIN "ZRCM_PRCD_ELEM" "=A33" ON ("/CMSBE/REPORT_01"."INVOICE_KEY" = "=A33"."INVOICEKEY" AND "=A33"."KSCHL" = N'ZE01' AND "/CMSBE/REPORT_01"."MANDT" = "=A33"."MANDT" )
LEFT OUTER MANY TO ONE JOIN "ZRCM_PRCD_ELEM" "=A34" ON ("/CMSBE/REPORT_01"."INVOICE_KEY" = "=A34"."INVOICEKEY" AND "=A34"."KSCHL" = N'ZE02' AND "/CMSBE/REPORT_01"."MANDT" = "=A34"."MANDT" ) 
LEFT OUTER MANY TO ONE JOIN "ZRCM_PRCD_ELEM" "=A35" ON ("/CMSBE/REPORT_01"."INVOICE_KEY" = "=A35"."INVOICEKEY" AND "=A35"."KSCHL" = N'ZE03' AND "/CMSBE/REPORT_01"."MANDT" = "=A35"."MANDT" ) 
LEFT OUTER MANY TO ONE JOIN "ZRCM_REP01_SUM" "=A36" ON ("/CMSBE/REPORT_01"."MANDT" = "=A36"."MANDT" AND "/CMSBE/REPORT_01"."INVOICE_KEY" = "=A36"."INVOICEKEY" ) 
LEFT OUTER MANY TO ONE JOIN "ZRCM_PRCD_ELEM" "=A37" ON ("/CMSBE/REPORT_01"."INVOICE_KEY" = "=A37"."INVOICEKEY" AND "=A37"."KSCHL" = N'ZEPD' AND "/CMSBE/REPORT_01"."MANDT" = "=A37"."MANDT" ) 
LEFT OUTER MANY TO ONE JOIN "ZRCM_AUDPRES_CAL" "=A38" ON ("/CMSBE/REPORT_01"."INVOICE_KEY" = "=A38"."INVOICEKEY" AND "=A38"."DISCOUNTTYPE" = N'07' AND "/CMSBE/REPORT_01"."MANDT" = "=A38"."MANDT" ) 
LEFT OUTER MANY TO ONE JOIN "ZRCM_AUDPRES_CAL" "=A39" ON ("/CMSBE/REPORT_01"."INVOICE_KEY" = "=A39"."INVOICEKEY" AND "=A39"."DISCOUNTTYPE" = N'08' AND "/CMSBE/REPORT_01"."MANDT" = "=A39"."MANDT" ) 
LEFT OUTER MANY TO ONE JOIN "ZRCM_AUDPRES_CAL" "=A40" ON ("/CMSBE/REPORT_01"."INVOICE_KEY" = "=A40"."INVOICEKEY" AND "=A40"."DISCOUNTTYPE" = N'06' AND "/CMSBE/REPORT_01"."MANDT" = "=A40"."MANDT" ) 
LEFT OUTER MANY TO ONE JOIN "ZRCM_PRCD_ELEM" "=A41" ON ("/CMSBE/REPORT_01"."INVOICE_KEY" = "=A41"."INVOICEKEY" AND "=A41"."KSCHL" = N'ZMWS' AND "/CMSBE/REPORT_01"."MANDT" = "=A41"."MANDT" ) 
WHERE --"/CMSBE/REPORT_01"."EPISODE_ID" IN ('2500004153') AND "/CMSBE/REPORT_01"."INVOICE_NUMBER"  IN ('000001000003882') AND
"=A3"."SRVDATE" IS NOT NULL
--AND "/CMSBE/REPORT_01"."EPISODE_ID" IN ('2500004523') 
AND SUBSTRING("=A3"."SRVDATE",1,6) = ('202603')
ORDER BY "=A3"."SRVDATE","/CMSBE/REPORT_01"."EPISODE_ID"

--SELECT * FROM "SAPHANADB"."/CMSBE/REPORT_01" WHERE "EPISODE_ID" IN ('2500004523') LIMIT 10



--SELECT * FROM  "SAPHANADB"."BKPF" WHERE BELNR = '3000001814' 
--LIMIT 10